Update dscribe to 2.0
duartegroup/mlp-train pull request #60
Opened 2023-10-22 23:59 UTC by juraskov

To add compatibility for numpy 1.24.3 required by the Cirrus facility,  I updated dscribe (needed for SOAP descriptor) to version 2.0

2023-10-23 00:00 UTC, danielhollas approved these changes
pair coded together :muscle:

2023-10-23 00:24 UTC, danielhollas requested changes
Still needs to relax the numpy requirement in requirements.txt

2023-10-23 08:59 UTC, Hanwen1018 commented
do we need to change the version requirement of numpy?

2023-10-24 09:20 UTC, danielhollas approved these changes

2023-10-24 10:17 UTC, Hanwen1018 approved these changes

2023-10-24 10:20 UTC, merged